package by.bsu.soap.service;


import by.bsu.soap.dto.MovieDto;
import by.bsu.soap.dto.RatingDto;
import by.bsu.soap.exception.ServiceException;
import by.bsu.soap.wrapper.MovieDtoArray;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "MovieService", targetNamespace = "http://service.soap.bsu.by/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MovieService {



  /**
   *
   * @return
   *     returns by.bsu.soap.wrapper.MovieDtoArray
   */
  @WebMethod
  @WebResult(partName = "return")
  MovieDtoArray retrieveAllMovies();


  /**
   *
   * @param arg0
   * @return
   *     returns by.bsu.soap.dto.MovieDto
   * @throws ServiceException
   */
  @WebMethod
  @WebResult(partName = "return")
  public MovieDto retrieveMovie(
      @WebParam(name = "arg0", partName = "arg0")
          long arg0)
      throws ServiceException
  ;

  /**
   *
   * @param arg0
   */
  @WebMethod
  void saveOrUpdateMovie(
      @WebParam(name = "arg0", partName = "arg0")
        MovieDto arg0);


  /**
   *
   * @param arg0
   */
  @WebMethod
  void deleteMovie(@WebParam(name = "arg0", partName = "arg0")
      long arg0);

  /**
   *
   * @param arg0
   */
  @WebMethod
  void rateAMovie(
      @WebParam(name = "arg0", partName = "arg0")
        RatingDto arg0);

}
